default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  min_messages: WARNING
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch('POSTGRESUSER', 'pguser') %>
  password: <%= ENV.fetch('POSTGRESPASS', 'pgpass') %>

development:
  <<: *default
  database: bucketlist_dev

test:
  <<: *default
  database: bucketlist_test
